#!/usr/bin/env bash

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d "./node_modules" ]; then
    echo "Directory /node_modules DOES NOT exists."
    echo "Running npm install"
    npm install
fi

NODE_ENV=production exec ./node_modules/.bin/rspack build --config rspack.config.js
