#!/usr/bin/env bash

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d "./node_modules" ]; then
    echo "Directory /node_modules DOES NOT exists."
    echo "Running npm install"
    npm install
fi

# Build in watch mode for development, writing directly to esphome_dashboard/static
exec ./node_modules/.bin/rspack build --watch --config rspack.config.js
