#!/usr/bin/env bash

if [ -z "$PORT" ]; then
  PORT=5006
fi

# Stop on errors
set -e

cd "$(dirname "$0")/.."

rm -rf dist

mkdir dist
cp -r ../raw_package/static dist/
cp -r static dist/static_web

node build/render-index.mjs

# Quit all background tasks when script exits
trap "kill 0" EXIT

cd ..

npm exec -- serve -p "$PORT" web.esphome.io/dist &
npm exec -- rollup --watch -c web.esphome.io/rollup.config.mjs
wait
